FROM python:3.12.2-alpine

# Set environment variables
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /code

# Copy the current directory contents into the container at /code
COPY . /code/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Expose port 8000 to the outside world
EXPOSE 8000

# Run Django app when the container launches
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "mockups.wsgi:application"]

