version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-django
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - db_volume:/db.sqlite3
    command: gunicorn --bind 0.0.0.0:8000 mockups.wsgi:application

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf/live/mockupseasy.com:/etc/letsencrypt/live/mockupseasy.com:ro
      - ./certbot/conf/archive/mockupseasy.com:/etc/letsencrypt/archive/mockupseasy.com:ro
      - ./staticfiles:/usr/share/nginx/html/static:ro
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw

volumes:
  db_volume:

