# Generated by Django 5.0.3 on 2024-03-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_mockuptemplate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockuptemplate',
            name='glb',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='mockuptemplate',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='mockuptemplate',
            name='templateImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
