# Generated by Django 4.2.1 on 2024-03-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='MockupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
                ('glb', models.FileField(upload_to='static/api')),
                ('description', models.TextField(max_length=5000)),
                ('templateImage', models.ImageField(upload_to='static/api')),
                ('image', models.ImageField(upload_to='static/api')),
                ('category', models.ManyToManyField(blank=True, to='api.category')),
            ],
        ),
    ]
