# Generated by Django 4.2.1 on 2024-03-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuptemplate',
            name='templateImageHeight',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mockuptemplate',
            name='templateImageWidth',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
