# Generated by Django 5.0.3 on 2024-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mockuptemplate_templateimageheight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockuptemplate',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='mockup_templates', to='api.category'),
        ),
    ]
