# Generated by Django 5.0.3 on 2024-03-07 20:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_mockuptemplate_glb_alter_mockuptemplate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockuptemplate',
            name='glb',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='glb/'),
        ),
        migrations.AlterField(
            model_name='mockuptemplate',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mockuptemplate',
            name='templateImage',
            field=models.ImageField(upload_to='templateImages/'),
        ),
    ]
